### ISSUE TITLE
Addon Validation Error

### ISSUE THREAD

**Issue by jo-va** [mozilla/addons#1263]
Please attach a copy of your add-on, and fill in the following information:

- Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

  When submitting a new version of an existing add-on.
  This happens when using `web-ext sign` or when uploading the add-on manually on the developer hub.

- Whether your add-on is listed or unlisted.

  The add-on is listed.

- The URL where you submitted the add-on.
  https://addons.mozilla.org/en-US/developers/addon/grammarly-1/versions/submit/

- The approximate time you submitted the add-on, with timezone.

  18:25 PDT, October 13

Here is the error message on the [generated report](https://addons.mozilla.org/en-US/developers/upload/989f28d536ea475691e21ccea50e8ff6):
```
Sorry, we couldn't load your WebExtension.

Error: Validation was unable to complete successfully due to an unexpected error.

Check https://developer.mozilla.org/en-US/Add-ons/WebExtensions to ensure your webextension is valid or file a bug at http://bit.ly/1POrYYU
```

Uploading a version manually also fails with the same error/report.

[firefox-grammarly-8.866.0.zip](https://drive.google.com/file/d/1l8rHxvFC4WVplptI-SwOyoesDxoYXyF5/view?usp=sharing)

Thank you.

**Comment by wagnerand** [comment]
Clicking the bug link above should have given you a template to fill out, as mentioned in my email. Can you please fill out the following form? (You can host your file elsewhere and link to it)

--- 

Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

* Whether your add-on is listed or unlisted.

* The URL where you submitted the add-on.

* The approximate time you submitted the add-on, with timezone.

**Comment by wagnerand** [comment]
@jo-va thank you for updating the initial comment. Replying here to trigger an email to involved AMO developers.

**Comment by jo-va** [comment]
Hi @wagnerand, we tried to re-upload the add-on around 20:20 PDT, October 22 but it is still failing with the same unexpected error. Here is the [generated report](https://addons.mozilla.org/en-US/developers/upload/ba9ebb68379441b09ceb86435e82284a).

And this is the submitted add-on: [firefox-grammarly-8.867.0.zip](https://drive.google.com/file/d/14SjeHdvfkRRvUE52TSE5gd7W302LnDGw/view?usp=sharing)

Thank you for your help.

**Comment by jo-va** [comment]
Hi @wagnerand, any idea what caused the above issue? Have you seen any similar problems with other add-ons?

Thank you.

**Comment by wagnerand** [comment]
I don't have new information at the moment, but I see you successfully submitted a new version on Oct 23.

**Comment by wagnerand** [comment]
We added an automatic retry as well as some internal optimizations regarding file handling and we believe this issue should be fixed now. I'll close it, please let us know if it keeps happening.
Thank you!

**Comment by jo-va** [comment]
Hi @wagnerand, thanks for your response. Unfortunately, we've encountered the same issue when trying to upload version 8.868 of our extension, so it seems the issue persists. It took several tries before the upload finally succeeded on December 20th.

We are currently trying to upload version 8.869.0, but we are having issues again. We tried many times; the first try was on Jan 8, 8:50 am PST, and the last one on Jan 11, 1:30 pm PST.

Thanks for your help.

**Comment by wagnerand** [comment]
@jo-va Sorry you are having troubles again. Could you also please attach the file you were trying to upload? Thank you!

**Comment by jo-va** [comment]
Sure, here is the add-on we tried to submit on Jan 11, 1:30 pm PST: [firefox-grammarly-8.869.0.zip](https://drive.google.com/file/d/1yHZZKKlFa_mWskVw-6rH6scyQIIcKXr7/view?usp=sharing)

**Comment by wagnerand** [comment]
Thank you!

@willdurand any ideas?

**Comment by gabebw** [comment]
@wagnerand Hi, I work on the same team as @jo-va, and unfortunately we've run into this issue again. The upload succeeded at about 4:30pm PST on May 26 after 12 tries. It is version 8.875.0.

Thank you for your help.

[firefox-grammarly-8.875.0.zip](https://drive.google.com/file/d/1TGASgashLZWSh9eaAeyPMxmpVBGG-IBT/view?usp=sharing)

**Comment by maikudou** [comment]
Hi, @wagnerand I work on the same extension as @gabebw and @jo-va . We can't upload our extension again with the same error. Can you suggest something?
[firefox-grammarly-8.877.0.zip](https://drive.google.com/file/d/1UEFfRtIl21W5x749kdeKQ-JzjA9cTaIg/view)

**Comment by maikudou** [comment]
@wagnerand It used to successfully work after several tries, now I've tried it 12 times and it fails with Unknown error

**Comment by luisincrespo** [comment]
@wagnerand Hello!

I also work on the same team as @gabebw, @jo-va, and @maikudou. We're still getting the "unexpected error" with our extension validation.

<img width="1011" alt="Screen Shot 2021-07-02 at 10 09 32 AM" src="https://user-images.githubusercontent.com/4452976/124308107-9ed18d80-db1d-11eb-8554-b50cb0d46829.png">

Do you have any updates on why this could be happening? Thanks!

**Comment by wagnerand** [comment]
Sorry for the delayed response.

Errors like these usually indicate the add-on bundling too much code. There isn't much i can suggest other than reducing the code in your JavaScript files.

**Comment by luisincrespo** [comment]
@wagnerand thanks for getting back to us.

What is the maximum file size to avoid the validation error?

**Comment by wagnerand** [comment]
Unless I am mistaken (cc @diox) there is a hard limit at 4MB per JS file, but validation can also fail if the add-on code is below that limit but it takes to long to complete due to structure or complexity of the code, or due to using several files close to the size limit.
