### ISSUE TITLE
Uploading large add-on returns 504 gateway timeout

### ISSUE THREAD

**Issue by kewisch** [mozilla/addons#622]
I've uploaded a [copy of Lightning](https://mozilla.kewis.ch/xpi/lightning-linux.xpi) to AMO and during the upload got a 504 gateway timeout message. This happens when POSTing to https://addons.mozilla.org/en-US/developers/addon/submit/upload-listed

Not sure if this is due to the size of the xpi or a broader issue. I've been noticing this since the weekend.

@jasonthomas any ideas?

**Comment by jasonthomas** [comment]
@bqbn can you take a look?

**Comment by bqbn** [comment]
I can't download the xpi file in the above comment.

How large is the file? Has the file size recently changed? And roughly, what's the speed of the network connection between your workstation and AMO website?

**Comment by kewisch** [comment]
I fixed the link, sorry. It is 4.5 MB large, which is not a change from the last beta. I have a 100/20 mbit line and it looks like at least in download it is being fully utilized, so I suspect the upload is similar.

**Comment by bqbn** [comment]
@kewisch, when was the last time the upload worked for you?

Using your file I was able to reproduce the 504 error once on -stage environment. However, when I looked at the application logs, I see that the file has been uploaded successfully, e.g.:

```
{
  "_index": "amo.olympia_web.docker.addons-2018-01-17",
  "_type": "amo.olympia_web.docker.addons",
  "_id": "AWEB5ufnY8Le047mQ62M",
  "_score": null,
  "_source": {
    "EnvVersion": "2.0",
    "Severity": 6,
    "Timestamp": "2018-01-17T02:15:00",
    "Hostname": "ip-172-31-22-60",
    "Pid": 16,
    "Fields": {
      "msg": "FileUpload created: 707102f4398a49198355495dbaef64a3"
    },
    "Logger": "http_app_addons",
    "Type": "z.devhub"
  },
  "fields": {
    "Timestamp": [
      1516155300000
    ]
  },
  "sort": [
    1516155300000
  ]
}
{
  "_index": "amo.olympia_web.docker.addons-2018-01-17",
  "_type": "amo.olympia_web.docker.addons",
  "_id": "AWEB5ufnY8Le047mQ62L",
  "_score": null,
  "_source": {
    "EnvVersion": "2.0",
    "Severity": 6,
    "Timestamp": "2018-01-17T02:14:59",
    "Hostname": "ip-172-31-22-60",
    "Pid": 16,
    "Fields": {
      "msg": "UPLOAD: '707102f4398a49198355495dbaef64a3_lightning-linux.xpi' (4705189 bytes) to '/mnt/efs/addons.allizom.org/files/temp/666068a268b8449fb801d45ac228fa9a.xpi'"
    },
    "Logger": "http_app_addons",
    "Type": "z.files"
  },
  "fields": {
    "Timestamp": [
      1516155299000
    ]
  },
  "sort": [
    1516155299000
  ]
}
```

The nginx layer has a 120-second read timeout for the application. The 504 might be because the timeout expired, and nginx closed the connection to the app.

However, it took less than a minute to upload the file and for the application to log the above messages. I'm not sure what the application does after it logs the above "upload success" message, and why it didn't send response to Nginx immediately after the successful upload.

Since we haven't changed either nginx or ELB settings for some time, can we get some dev help to check if something has changed between 12/7/2017 and 1/9/2018 releases that might have contributed to the timeout?

**Comment by kewisch** [comment]
I can say for sure it last worked for me on October 10th 2017. I have not uploaded any versions in between.

**Comment by muffinresearch** [comment]
@bqbn here's the changeset for addons-server https://github.com/mozilla/addons-server/compare/2017.12.07...2018.01.11

**Comment by muffinresearch** [comment]
@diox, @EnTeQuAk, @eviljeff  - do any of you have any thoughts about anything that might have changed in this timeframe (including deps) that may have impacted uploads?

**Comment by diox** [comment]
In terms of code there isn't much in there that should have had any impact... There were some changes to how we handle tmp paths but that's mostly for tests, shouldn't have impacted prod, and in any case it's not the task that extracts the add-on that fails but rather the upload itself...

Could be a dependency but that's harder to check. Is it possible to deploy 2017.12.07 somewhere to check that it really works ? And if not, go further back ?

**Comment by bqbn** [comment]
So I tested uploading a bigger size file (5.6MB) [1] on -stage, and was able to upload the file successfully without 504 errors.

Nginx showed the expected log messages.

```
1516321359.048 "23.81.178.86" "POST /en-US/developers/addon/submit/distribution HTTP/1.1" 302 5 "https://addons.allizom.org/en-US/developers/addon/submit/distribution" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0" 0.027 0.027 "-"
1516321437.064 "23.81.178.86" "POST /en-US/developers/upload HTTP/1.1" 302 5 "https://addons.allizom.org/en-US/developers/addon/submit/upload-listed" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0" 66.141 60.598 "-"
```
From which you can see it took `60.598` seconds for Nginx to get the 302 response back.

Looking at the application log, I see not only the `FileUpload created` message, but also some message that indicates the file was processed, for example,

```
"msg": "Time to process and save upload validation; upload.pk=34518; processing_time=60000; scaled_per_mb=10635.22568929980457012781462; upload_size_in_mb=5.64162921905517578125; created=2018-01-19 00:23:00; now=2018-01-19 00:24:00.522840"
```

My hypothesis is that there is something in your file that made the application spend more time processing it (e.g.: more time than 120 seconds, and more time than it needed to process a bigger file).

[1] https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/versions/?page=1#version-2.0.0

**Comment by bqbn** [comment]
And a question for the dev team. :)

Is it possible to make the application return 302 immediately after a file is uploaded and an async job is submitted? 

From the above example, it seems like the application waited until celery finished the "process and save upload validation" job before it returned 302 to nginx. This holds up the connection, and it seems to me that it defeats the purpose of doing **asynchronous** validation.

**Comment by diox** [comment]
> Is it possible to make the application return 302 immediately after a file is uploaded and an async job is submitted?

That's already what should be happening. 

IIRC (and I'm not sure, would have to re-check) what we do is the extraction and initial manifest parsing (not validation/linting) directly in the upload view, but the validation itself definitely happens in a celery task that we don't wait for.

**Comment by bqbn** [comment]
> > Is it possible to make the application return 302 immediately after a file is uploaded and an async job is submitted?

> That's already what should be happening.

Assuming it's already happening, wouldn't it mean that he would not have seen 504 in the first place? After all, it took less than 1 minute for the application to log the "FileUpload created" message when I tested uploading his file.

And in the second case when I tested a bigger sized file, the time it took for nginx to get the 302 roughly matches the time it took for celery to finish processing the validation, i.e. 60 seconds (please see the log messages in [my previous comment](https://github.com/mozilla/addons/issues/622#issuecomment-358836495)).

**Comment by bqbn** [comment]
> Edit: it's easy to test btw. Stop the celery workers, upload a new file. You should see the 302 response (absence of workers to process the queue doesn't matter to put the task in the queue) followed by a ton of GET requests inquiring about the status of the fileupload, which will only end when the workers are turned back on to process the file :)

Thanks for the test idea. :)

I stopped the celery workers on -stage and did the following tests.

I first tested the Decentraleyes addon (the bigger sized addon), and can confirm that what you described is the case. However, it still took nginx 61 seconds to get a response (it took about 20 seconds from I clicked the "select a file" button to the app logged ""FileUpload created" message). There isn't enough log info to tell what the app is doing during the rest of the 40'ish seconds, so I'm guessing it was unzipping and parsing the file like you mentioned earlier?


I then tested the Lighting addon, and got a 504 still. It took about 7 seconds from clicking the "select a file" button to the app logging ""FileUpload created" message. Then eventually, nginx gave up and logged a 504.
```
1516339967.803 "23.81.178.86" "POST /en-US/developers/upload HTTP/1.1" 504 176 "https://addons.allizom.org/en-US/developers/addon/submit/upload-listed" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0" 124.767 120.035 "-"
```

I also notice that after the celery workers are started up again, the Lighting addon got processed eventually.
```
"msg": "Time to process and save upload validation; upload.pk=34520; processing_time=1444000; scaled_per_mb=321802.9592435075402922178046; upload_size_in_mb=4.48721790313720703125; created=2018-01-19 05:30:51; now=2018-01-19 05:54:55.591110"
```
It seems to me the app did submit the job to rabbitmq at the time when it logged the "FileUpload created" message. However, I'm not sure why the app didn't return 302 to nginx for this file.

**Comment by CAPizzas** [comment]
I've had this same problem. A private distribution add-on that signed just fine January 5, and now I get a 504 status error every time I try to upload an update. The only changes I made to the files since the last time it was signed were minor html, not logic, so I think there was an update or something. I've tried different browsers, computers, and recompling the zip file. Nothing has allowed it to work.

**Comment by diox** [comment]
@CAPizzas : sorry about that. Your feedback helps, that confirms it's definitely a recent regression. Can you give some information about the size of your add-on, and the number of files in it? That might help us pinpoint the cause of the problem.

**Comment by diox** [comment]
@EnTeQuAk after investigating a little more, I'm suspecting this is because of the `TMP_PATH` changes in https://github.com/mozilla/addons-server/commit/778a94871a07e6ff1aaf2a199fb72387b5829ab8

Before that commit, we used to extract in the default directory for `NamedTemporaryFile`, which is `tempfile.gettempdir()`, which should be `/tmp`. We are now using `settings.TMP_PATH`

However on dev and stage, and presumably prod as well, `settings.TMP_PATH` is *not* `/tmp`, but instead something living in efs. For instance, on stage, it is `/mnt/efs/addons.allizom.org/shared_storage/tmp`. My theory is that it's what makes the extraction we perform before the actual validation way slower, thus causing the 504s, because writing to efs is slower than writing to whatever `/tmp` points to.

(I initially thought the fact that files bigger than `settings.FILE_UPLOAD_MAX_MEMORY_SIZE` - 2.5 MB - are initially stored in `/tmp` instead of memory would play a role in this, but I don't think it's the case, ultimately at some point we will have to move the upload to EFS, so that's fine. I think the problem is really doing the extraction itself on EFS)

**Comment by AlexandraMoga** [comment]
I've uploaded a copy of https://addons.mozilla.org/en-US/firefox/addon/lastpass-password-manager/ ( ~10 MB) on dev and stage and the submission went well. The process took ~50s to complete and no errors were thrown. 
It seems this should be fixed now.

**Comment by kewisch** [comment]
I'm still getting the 504 with the xpi attached in the initial comment.

**Comment by diox** [comment]
@kewisch : where are you testing? This hasn't landed in prod yet.

**Comment by kewisch** [comment]
Duh, sorry about that!

**Comment by diox** [comment]
No worries, it should be landing in prod later today, when we push the tag.
