### ISSUE TITLE
Croatian Dictionary add-on doesn't work on last version of Firefox and how to FIX it

### ISSUE THREAD

**Issue by emaus78** [mozilla/addons#634]
**PROBLEM**
-Go to https://addons.mozilla.org/en-US/firefox/language-tools/
-Find Croatian dictionary.
-URL is https://addons.mozilla.org/en-US/firefox/addon/croatian-dictionary-hrvatski-r/
-Try to install it.
-Doesn't work, because it is not compatible with few last firefox updates.

**SOLUTION**
-Go on another Croatian dictionary
-URL is https://addons.mozilla.org/en-US/firefox/addon/croatian-dictionary-hrvat-9795/
-Try to install it
-Compatible and works!

**FIX**
Please update official add-ons page to working add-on! 

Thank you and kind regards

**Comment by jvillalobos** [comment]
This should be fixed shortly. I removed the incompatible dictionary and changed the target locale of the functional one. It had its locale set to `hr-HR`, which apparently isn't supported by AMO (it supports `hr`).

**Comment by AlexandraMoga** [comment]
I am still seeing the old incompatible dictionary on the language tools page - AMO prod:
Also, shouldn't there be an incompatibility banner displayed on the dictionary page to know that it is incompatible before attempting to install it?

![image](https://user-images.githubusercontent.com/31961530/36250086-70559fc2-1245-11e8-821a-8e8db5d68bd0.png)

**Comment by diox** [comment]
Not sure what's going on here but AMO always considers dictionaries are compatible by design.

**Comment by jvillalobos** [comment]
It should be fixed now. I'm not sure why the usual editing form isn't working.

As for compatibility, dictionaries are generally compatible with all future versions of Firefox. There have been one or two changes to dictionaries that break backward compatibility along the years, and it looks like AMO wasn't updated to flag them.

**Comment by AlexandraMoga** [comment]
Verified again on AMO prod, FF58 and the correct dictionary is displayed now:

![hr dic](https://user-images.githubusercontent.com/31961530/36297970-40de81aa-12fe-11e8-8bd0-b8613127b633.gif)
